services:
# Command
    Oka\WSSEAuthenticationBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
        arguments: ['@oka_wsse_authentication.util.wsse_user_manipulator']

# Security
    oka_wsse_authentication.object_manager:
        class: Doctrine\Common\Persistence\ObjectManager

# Security
    oka_wsse_authentication.wsse_request_matcher:
        class: Oka\WSSEAuthenticationBundle\Http\WSSERequestMatcher

# Util
    oka_wsse_authentication.util.wsse_user_manipulator:
        class: Oka\WSSEAuthenticationBundle\Util\WSSEUserManipulator
        arguments: ['', '@event_dispatcher', '']
